# Generated by Django 2.1.5 on 2019-02-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoser_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mid', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mem',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
